version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      - API_ID=your_api_id
      - API_HASH=your_api_hash
      - CHAT_ID=your_chat_id
      - INSTAGRAM_USERNAME=your_instagram_username
      - INSTAGRAM_PASSWORD=your_instagram_password
    volumes:
      - .:/app
